### ISSUE TITLE
Failing build because of `yield` keyword

### ISSUE THREAD

**Issue by mistadikay** [babel/babili#103]
I have errors like these when building with `babel-preset-babili`:

```
ERROR in ./src/redux/sagas/landing-menu.js
Module build failed: SyntaxError: The keyword 'yield' is reserved (1:2367)
    at Parser.pp.raise (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.parseIdent (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1464:240)
    at Parser.pp.parseExprAtom (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1090:21)
    at Parser.pp.parseExprSubscripts (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1004:19)
    at Parser.pp.parseExprOps (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:948:19)
    at Parser.pp.parseMaybeConditional (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:930:19)
    at Parser.pp.parseMaybeAssign (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:908:19)
    at Parser.pp.parseVar (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2743:24)
    at Parser.pp.parseVarStatement (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2637:8)
    at Parser.pp.parseStatement (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2437:19)
    at Parser.pp.parseBlock (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseFunctionBody (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:1413:22)
    at Parser.pp.parseFunction (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2770:8)
    at Parser.pp.parseFunctionStatement (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2540:15)
    at Parser.pp.parseStatement (PROJECT_FOLDER/node_modules/acorn/dist/acorn.js:2420:19)
 @ ./src/redux/sagas/index.js 1:285-310
```

My `.babelrc`:

``` json
{
  "presets": [ "es2015", "stage-1", "react" ],
  "plugins": [
    "transform-runtime",
    "transform-decorators-legacy"
  ],
  "env": {
    "production": {
      "presets": ["babili"],
      "plugins": [
        "transform-react-inline-elements",
        "transform-react-constant-elements"
      ]
    }
  }
}
```

**Comment by mistadikay** [comment]
Please let me know if there any missing info I should provide

**Comment by hzoo** [comment]
The error is coming from `node_modules/acorn/dist/acorn.js` so webpack?

Can you provide a small repro code snippet? But maybe it's just not transpiling `yield`.

**Comment by mistadikay** [comment]
I think I found the problematic part:
```js
// this code snippet causes an error mentioned above
const { language, platform } = yield select(getPageParams);
```

```js
// with this code snippet everything transpiles smoothly
const params = yield select(getPageParams);
```

**Comment by mistadikay** [comment]
I can probably create a repo where this error can be reproduced. Let me know if you need that

**Comment by hzoo** [comment]
Yeah that would be good if you can

**Comment by mistadikay** [comment]
Sure thing: https://github.com/mistadikay/babili-yield-bug

Just run `npm run build` and you will see the error

**Comment by mistadikay** [comment]
Updated the repo with webpack CLI option. If you run `npm run webpack`, build is working. Could it be https://github.com/start-runner/simple-cli messing up something?

**Comment by mistadikay** [comment]
Nope, it's not start-runner. Removed it and build is still failing. Please see updated repo.
p.s.: sorry for the noise, just trying to help as much as I can 😕

**Comment by danez** [comment]
I just tried different combinations, and removing the plugin `babel-plugin-transform-merge-sibling-variables` from the babili preset makes the example work.

**Comment by hzoo** [comment]
Oh interesting.

```js
function* onPageSave({ payload }) {
    const { language, platform } = yield select(getPageParams);
}
```

```js
"use strict";

var _marked = [onPageSave].map(regeneratorRuntime.mark);

function onPageSave(_ref) {
    var a = _ref.payload,
        _ref2 = yield select(getPageParams),
        b = _ref2.language,
        c = _ref2.platform;

    return regeneratorRuntime.wrap(function onPageSave$(_context) {
        for (; 1;) switch (_context.prev = _context.next) {
            case 0:
            case "end":
                return _context.stop();
        }
    }, _marked[0], this);
}
```

add `"minified: false"` in the .babelrc to get whitespace back. It looks like it's combining the variables like @danez mentioned and yield isn't transformed

**Comment by hzoo** [comment]
This works with `"passPerPreset": true` - forgot what we decided to do (add it to minify preset?)

**Comment by DylanPiercey** [comment]
I ran into the same issue and realized I posted a duplicate.
I left what info I could find in https://github.com/babel/babili/issues/149.

**Comment by iam4x** [comment]
Any update on this? Since options are not released yet?

**Comment by kangax** [comment]
We just need to release an update ASAP, since `passPerPreset = false` is really too troublesome.

**Comment by boopathi** [comment]
passPerPreset is by default enabled in babili.
