### ISSUE TITLE
"Error: spawn UNKNOWN"

### ISSUE THREAD

**Issue by Daniel15** [babel/babili#108]
When trying to use the CLI version:
```
node_modules\.bin\babili.cmd -d .

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:367:9)
    at Object.<anonymous> (C:\temp\babilitest\node_modules\babili\lib\index.js:16:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

Windows 10, Node v5.7.1 (I should probably upgrade Node, guess)

**Comment by Daniel15** [comment]
It works if I run `Babel` directly:
```
node_modules\.bin\babel.cmd --presets=babili in\test.js

function helloWorld(){foo()}helloWorld();
```

**Comment by hzoo** [comment]
```
import child from "child_process";

const args = process.argv.slice(2).concat(["--presets=babili"]);

const opts = {
  stdio: "inherit",
  env: process.env,
};

child.spawn(require.resolve("babel-cli/bin/babel"), args, opts);
```

must be an issue with child.spawn like in lerna?

**Comment by Daniel15** [comment]
Yeah... Windows doesn't use shebangs, so executing a JavaScript file directly won't work. Instead, you'll probably have to execute `node` directly:
```
import child from "child_process";

const args = [require.resolve("babel-cli/bin/babel")]
  .concat(process.argv.slice(2).concat(["--presets=babili"]));

const opts = {
  stdio: "inherit",
  env: process.env,
};

child.spawn('node', args, opts);
```

That is, run `node babel-cli/bin/babel.js` rather than just `babel-cli/bin/babel`. It should work the same as what it's currently doing.

**Comment by hzoo** [comment]
Ok cool didn't know that - do you want to pr that one?
