### ISSUE TITLE
Unexpected UnaryExpression. Expected an Identifier

### ISSUE THREAD

**Issue by jbt** [babel/babili#122]
I'm seeing the above error when I have lots of nested if/else's with the occasional empty block.

<details>
  <summary>Stack trace if it's useful</summary>
```
Error: test.js: Unexpected UnaryExpression. Expected an Identifier
    at Mangler.renameNew (foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:193:19)
    at foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:143:23
    at Array.map (native)
    at Scopable (foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:135:16)
    at NodePath._call (foo/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (foo/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (foo/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (foo/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (foo/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (foo/node_modules/babel-traverse/lib/context.js:190:19)

```
</details>

Minimum example I could come up with ([repl](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=es2015&experimental=true&loose=false&spec=false&code=function%20foo()%20%7B%0A%20%20var%20a%2C%20b%2C%20c%3B%0A%20%20%0A%20%20if%20(a)%20%7B%0A%20%20%20%20if%20(b)%20%7B%0A%20%20%20%20%20%20if%20(c)%20%7B%7D%0A%20%20%20%20%7D%0A%20%20%7D%20else%20%7B%0A%20%20%20%20if%20(b)%20%7B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20if%20(c)%20%7B%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D))

```js
function foo() {
  var a, b, c;
  
  if (a) {
    if (b) {
      if (c) {}
    }
  } else {
    if (b) {
    } else {
      if (c) {}
    }
  }
}
```

Seems to be coming from the interaction of `minify-dead-code-elimination` and `minify-mangle-names` (both seem fine individually but fail when used together)

Error's being thrown [here](https://github.com/babel/babili/blob/e306bf1b644f004145f7771f599e2b97401c5eac/packages/babel-plugin-minify-mangle-names/src/index.js#L168) which suggests it might be an upstream Babel bug?

**Comment by boopathi** [comment]
Thanks for reporting.

It's an issue with mangler. Will take a look.

**Comment by jbt** [comment]
Nice one! 👍
