### ISSUE TITLE
Module build failed: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by frux** [babel/babili#138]
Hello!
I added babili to my webpack config and I've just got this error.

```
Module build failed: TypeError: /Users/frux/Projects/patterns/frontend/client/app.jsx: Cannot read property 'node' of undefined
        at Mangler.rename (/Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:186:26)
        at /Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:141:23
        at Array.map (native)
        at Scopable (/Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:133:16)
        at NodePath._call (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:105:12)
        at TraversalContext.visitQueue (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/index.js:161:17)
        at NodePath.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitMultiple (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:103:17)
        at TraversalContext.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:190:19)
        at Function.traverse.node (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/index.js:161:17)
        at traverse (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/index.js:83:12)
        at NodePath.traverse (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/index.js:144:25)
        at Mangler.mangle (/Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:98:22)
        at Mangler.run (/Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:43:14)
        at PluginPass.Program (/Users/frux/Projects/patterns/frontend/node_modules/babel-plugin-minify-mangle-names/lib/index.js:227:17)
        at newFn (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/visitors.js:276:21)
        at NodePath._call (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/path/context.js:105:12)
        at TraversalContext.visitQueue (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/index.js:161:17)
        at traverse (/Users/frux/Projects/patterns/frontend/node_modules/babel-traverse/lib/index.js:83:12)
     @ ./client/router.jsx 1:977-993
```

My babel-loader config:
```js
{
	test: /\.jsx?$/,
	exclude: /node_modules\/(?!(y-|react-base-component))/,
	loader: 'babel',
	query: {
		presets: ['es2015', 'stage-0', 'react'],
		env: {
			production: {
				presets: ['es2015', 'stage-0', 'react', 'babili']
			}
		}
	}
}
```

**Comment by hzoo** [comment]
If you could also add a minimal code snippet that would help greatly

**Comment by frux** [comment]
Sure! Here is app.jsx which is the first in the stacktrace:

```js
import React from 'react';
import Helmet from 'react-helmet';
import BaseComponent from 'react-base-component';
import {showModal, hideModal} from './actions/page';

import './app.css';

import YHeader from './blocks/y-header';
import YFooter from './blocks/y-footer';

export default class App extends BaseComponent {
	constructor(props) {
		super(props);
		this._bind(
			'handleConfirmOpen',
			'handleConfirmClose'
		);
	}

	handleConfirmOpen() {
		showModal({
			name: 'confirm'
		});
	}

	handleConfirmClose() {
		hideModal('confirm');
	}

	render() {
		const {...props} = this.props;
		return (
			<div className="app"}>
				<Helmet
					htmlAttributes={{lang: 'en'}}
					title="Test"
					meta={[
						{name: 'description', content: 'React application'},
						{property: 'og:type', content: 'website'}
					]}
					link={[
						{rel: 'stylesheet', href: '/static/index.build.css'},
						{rel: 'icon', href: '/static/favicon.png'}
					]}
					script={[
						{src: '//cdnjs.cloudflare.com/ajax/libs/immutable/3.8.1/immutable.js'},
						{src: '/static/vendors.build.js'}
					]}
					/>
				<YHeader/>
				<div className="bundle">{props.children}</div>
				<YFooter/>
			</div>
		);
	}
}

App.propTypes = {
	children: React.PropTypes.object.isRequired
};
```

**Comment by frux** [comment]
Also I've just repeated this problem in REPL using this snippet.
