### ISSUE TITLE
babili with browserify + babelify error on production build

### ISSUE THREAD

**Issue by jeromecovington** [babel/babili#150]
This is my `browserify` configuration in `package.json`.
```
"browserify": {
  "extensions": [
    ".js",
    ".jsx"
  ],
  "transform": [
    [
      "babelify",
      {
        "presets": [
          "es2015",
          "react"
        ],
        "env": {
          "production": {
            "presets": [
              "babili"
            ]
          }
        },
        "plugins": [
          "transform-class-properties",
          "transform-async-to-generator",
          "transform-object-rest-spread",
          "transform-runtime",
          "../../../lib/utils/babelRelayPlugin"
        ]
      }
    ],
    [
      "envify"
    ]
  ]
}
```

But whenever I do a production build, I get the following error:
```
TypeErrorr /home/computer/project/lib/app/views/components/ArticleHeader.jsx: Property expressions[0] of SequenceExpression expected node to be of a type ["Expression"] but instead got undefined
    at validate (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-types/lib/definitions/index.js:109:13)
    at validator (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-types/lib/definitions/index.js:57:7)
    at Object.validate (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-types/lib/definitions/index.js:190:10)
    at validate (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-types/lib/index.js:466:7)
    at bail (/home/computer/project/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-simplify/node_modules/babel-helper-to-multiple-sequence-expressions/lib/index.js:40:21)
    at _loop (/home/computer/project/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-simplify/node_modules/babel-helper-to-multiple-sequence-expressions/lib/index.js:96:16)
    at convert (/home/computer/project/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-simplify/node_modules/babel-helper-to-multiple-sequence-expressions/lib/index.js:102:20)
    at toMultipleSequenceExpressions (/home/computer/project/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-simplify/node_modules/babel-helper-to-multiple-sequence-expressions/lib/index.js:10:17)
    at PluginPass.enter (/home/computer/project/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-simplify/lib/index.js:557:39)
    at newFn (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/computer/project/node_modules/babelify/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
```

I made sure to update `babelify` in order to have `babel-core@6.14`.

**Comment by hzoo** [comment]
It would be great to get a minimal code snippet since we don't have enough information to reproduce with this

**Comment by jeromecovington** [comment]
Sure thing, what kind of code snippet would help?

**Comment by hzoo** [comment]
I would reduce `/home/computer/project/lib/app/views/components/ArticleHeader.jsx` so that it still reproduces the error if that's possible

**Comment by jeromecovington** [comment]
Yep, let me see if I can do just that. May take a few.

**Comment by jeromecovington** [comment]
So the offending code seems to be in the render method of that component, where we have:
```
...some jsx...
{/* eslint-disable react/no-danger */}
...some jsx that uses dangerouslySetInnerHTML...
{/* eslint-disable react/no-danger */}
...some more jsx...
```

If I remove the blocks with `eslint-disable` comments, the build completes without issue. Which kind of makes sense considering the error:
```
Property expressions[0] of SequenceExpression expected node to be of a type ["Expression"] but instead got undefined
```

As those blocks in the render method have only got comments, and if evaluated as expressions would evaluate to `undefined`.

**Comment by jeromecovington** [comment]
If those comments are moved out of the expression blocks, the file seems parseable. Closing, thanks for getting this on the right path, @hzoo!

**Comment by hzoo** [comment]
I think it's still weird - must be a combination of things though since it's fine in the [repl](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=true&presets=es2017%2Creact&experimental=false&loose=false&spec=false&code=class%20A%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Casdf%3E%0A%20%20%20%20%20%20%20%20%3Ca%3E%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%7B%2F*%20eslint-disable%20react%2Fno-danger%20*%2F%7D%0A%20%20%20%20%20%20%20%20%3Ca%3E%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%7B%2F*%20eslint-disable%20react%2Fno-danger%20*%2F%7D%0A%20%20%20%20%20%20%3C%2Fasdf%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0AA()%3B&playground=true)

**Comment by ryanez** [comment]
I'm having a problem like that one when I activate the Minify, here the [repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Creact&code=%0Afunction%20component(React%2C%20Route%2C%20Login%2C%20App%2C%20Home)%20%7B%0A%0A%20%20return%20%5B%0A%20%20%20%20%20%20%3CRoute%20path%3D%22%2Flogin%22%20component%3D%7BLogin%7D%20key%3D%22login%22%2F%3E%2C%0A%20%20%20%20%20%20%3CRoute%20name%3D%22Root%22%20path%3D%22%2F%22%20component%3D%7BApp%7D%20key%3D%22app%22%20onEnter%3D%7BverifyLoggedIn%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CRoute%20path%3D%22*%22%20component%3D%7BHome%7D%20%2F%3E%0A%20%20%20%20%20%20%3C%2FRoute%3E%0A%20%20%5D%3B%0A%20%20%0A%20%20function%20verifyLoggedIn()%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%7D&experimental=false&loose=false&spec=false&playground=true)

I'm seeing "repl: Unexpected JSXIdentifier. Expected an Identifier", any clue?

**Comment by boopathi** [comment]
@ryanez Probably related to #158

**Comment by ryanez** [comment]
Thanks already looked into that one, and after hours of no success switched to es2015 + uglifyJS
