### ISSUE TITLE
Possible conflict with transform-react-constant-elements?

### ISSUE THREAD

**Issue by f0rr0** [babel/babili#195]
Using this with `transform-react-constant-elements` produces a cryptic error:
```
Module build failed: Error: /Users/...path../: File/Program node, we can't possibly find a statement parent to this
```

Everything's ok without `transform-react-constant-elements`.

Full stack trace:
```
at NodePath.getStatementParent (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/family.js:43:11)
    at PathHoister.getAttachmentPath (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/lib/hoister.js:110:26)
    at PathHoister.run (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/lib/hoister.js:160:25)
    at NodePath.hoist (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/modification.js:263:18)
    at PluginPass.JSXElement (/Users/sid/Dev/bridg-email-designer/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:39:16)
    at newFn (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/sid/Dev/bridg-email-designer/node_modules/babel-traverse/lib/context.js:150:16)
 @ ./components/App.jsx 1:25-58
 @ ./index.jsx
```

**Comment by boopathi** [comment]
Duplicate #194
