### ISSUE TITLE
Bundle minification fails when used with webpack CommonsChunkPlugin

### ISSUE THREAD

**Issue by vamsiampolu** [babel/babili#296]
I run webpack using either of the following scripts:

```json
{
  "build:prod": "cross-env NODE_ENV=production webpack",
  "build:prod:dash": "cross-env NODE_ENV=production webpack-dashboard -- webpack",
}
```

The webpack config for production looks like this:

```
const APP_PATH = path.resolve('./app');
const BUILD_PATH = path.resolve('./build');
const TEST_PATH = path.resolve('./test');
const merge = require('webpack-merge');
const vendor = Object.keys(require('./package.json').dependencies);

const base = {
  entry: `${APP_PATH}/index.js`,
  output: {
    filename: 'bundle.js',
    path: BUILD_PATH,
    publicPath: '/css-in-js-test/',
  },
  devtool: 'eval-source-map',
  module: {
    loaders: [
      {
        test: /\.jsx?/,
        loader: 'babel',
        include: [APP_PATH],
      },
      {
        test: /\.svg$/i,
        loader: 'svg-sprite!svgo',
      },
      {
        test: /\.json$/,
        loader: 'json',
      },
    ],
  },
  plugins: [
    new DashboardPlugin(),
  ],
};

const prod = {
  entry: {
    app: `${APP_PATH}/index.js`,
    vendor,
  },
  output: {
    filename: '[name].js',
    path: BUILD_PATH,
    publicPath: '/css-in-js-test/',
  },
  devtool: 'source-map',
  plugins: [
    new DefinePlugin({
      NODE_ENV: JSON.stringify('production'),
    }),
    new CommonsChunkPlugin({
      names: ['vendor', 'manifest'],
    }),
  ],
};


const html = {
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Bookcover mashup',
      inject: false,
      mobile: true,
      appMountId: 'root',
      template,
    }),
  ],
};

//within a switch case based on `npm_lifecycle_event`:
console.log('Production config with minification and bundle splitting');
config = merge(base, prod, html);
break;
```

I see this error when using `babili` with the webpack setup described above:

```bash
ERROR in ./app/Book.js
Module build failed: TypeError: /home/vamsi/Do/css-in-js-test/app/Book.js: t.isNodesEquivalent is not a function
    at visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-plugin-minify-simplify/lib/index.js:386:27)
    at visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-plugin-minify-simplify/lib/index.js:369:23)
    at PluginPass.visitor.ConditionalExpression.exit.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-plugin-minify-simplify/lib/index.js:395:22)
    at newFn (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/vamsi/Do/css-in-js-test/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./app/Bookshelf.js 1:308-325

```

**Comment by boopathi** [comment]
This requires latest version of babel-types - `6.19.0` which is available with the latest version of babel-core.

**Comment by vamsiampolu** [comment]
@boopathi 

I am using the following babel packages:

```
"babel": "^6.5.2",
    "babel-cli": "^6.18.0",
    "babel-core": "6.18.2",
    "babel-eslint": "^7.1.0",
    "babel-loader": "6.2.7",
    "babel-plugin-transform-class-properties": "6.11.5",
    "babel-plugin-transform-es2015-classes": "6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-polyfill": "6.16.0",
    "babel-preset-babili": "0.0.9",
    "babel-preset-env": "0.0.7",
    "babel-preset-react": "^6.16.0",
    "babel-register": "6.18.0",
```

**Comment by boopathi** [comment]
Can you see the version of `babel-types` ? It should be `6.19.0`.

**Comment by vamsiampolu** [comment]
I have installed `babel-types`, how do I configure it to work in my `.babelrc`

**Comment by boopathi** [comment]
You don't have to configure it...

babel-core fetches babel-types and the version in babel-core wasn't updated to use the latest version of babel-types. 

So for now, you just have to ensure that babel-types required by babel-core is 6.19.0.

**Comment by vamsiampolu** [comment]
Looks like I was using node v6.2.0, switching to node v7.1.0 fixed the issue for me. Thanks

**Comment by vamsiampolu** [comment]
@boopathi I moved to the `babili-webpack-plugin` and it now minifies all my `bundles`.
