### ISSUE TITLE
Benchmark run error

### ISSUE THREAD

**Issue by boopathi** [babel/babili#309]
> Reported by @shinew in https://github.com/babel/babili/pull/286#issuecomment-263990547

I tried running the benchmark (`./scripts/benchmark.js react@0.14.3 react/dist/react.js`), but I got an error (below). This was on `master`.

<details>

```
/Users/shinew/dev/babili/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

TypeError: unknown: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got undefined
    at Object.validate (/Users/shinew/dev/babili/node_modules/babel-types/lib/definitions/index.js:109:13)
    at validate (/Users/shinew/dev/babili/node_modules/babel-types/lib/index.js:511:9)
    at Object.builder (/Users/shinew/dev/babili/node_modules/babel-types/lib/index.js:472:7)
    **at liftDeclaration (/Users/shinew/dev/babili/packages/babel-plugin-transform-merge-sibling-variables/lib/index.js:31:29)**
    at PluginPass.ForStatement (/Users/shinew/dev/babili/packages/babel-plugin-transform-merge-sibling-variables/lib/index.js:44:9)
    at newFn (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/shinew/dev/babili/node_modules/babel-traverse/lib/path/context.js:115:19)
```

</details>

/cc @vigneshshanmugam

**Comment by vigneshshanmugam** [comment]
@boopathi will take a look..

**Comment by vigneshshanmugam** [comment]
I tried it on latest `master` and with node 6.5.0.. I am actually getting the result.

**Comment by vigneshshanmugam** [comment]
may be an issue in old `babel-core` ? https://github.com/babel/babel/issues/2860

**Comment by shinew** [comment]
Error still here. Running OSX 10.12.1, node v6.8.1.

Steps to repro:
```bash
git clone https://github.com/babel/babili.git
cd babili
npm install
npm run bootstrap
npm run build
./scripts/benchmark.js react@0.14.3 react/dist/react.js
```

Let me know if you need any other info. It'd be helpful if someone else can verify the above steps lead to the error.

**Comment by vigneshshanmugam** [comment]
@shinew Thanks.. I can able to reproduce now. found the bug in the code. Will create a PR soon.
