### ISSUE TITLE
babel-preset-babili does not accept options

### ISSUE THREAD

**Issue by blai** [babel/babili#341]
Something simple as the following config won't work

```json
{
  "presets": [
    ["babili", { "mangle": { "blacklist": ["foo"] } }]
  ]
}
```

Dig into installed `babel-preset-babili` source in `node_modules`, saw the content of `lib/index.js` as

```js
"use strict";

module.exports = {
  minified: true,
  plugins: [require("babel-plugin-minify-constant-folding"), require("babel-plugin-minify-dead-code-elimination"), require("babel-plugin-minify-flip-comparisons"), require("babel-plugin-minify-guarded-expressions"), require("babel-plugin-minify-infinity"), require("babel-plugin-minify-mangle-names"), require("babel-plugin-minify-numeric-literals"), require("babel-plugin-minify-replace"), require("babel-plugin-minify-simplify"), require("babel-plugin-minify-type-constructors"), require("babel-plugin-transform-member-expression-literals"), require("babel-plugin-transform-merge-sibling-variables"), require("babel-plugin-transform-minify-booleans"), require("babel-plugin-transform-property-literals"), require("babel-plugin-transform-regexp-constructors"), require("babel-plugin-transform-remove-undefined"), require("babel-plugin-transform-simplify-comparison-operators"), require("babel-plugin-transform-undefined-to-void")]
};
```

Per documentation, looks like we do want to accept options, can we please enable it? Thanks.

**Comment by dotnetCarpenter** [comment]
Got the same issue. `./node_modules/.bin/babel js/src/main.js --presets babili --minified`

Error:

```
./node_modules/.bin/babel js/src/main.js --presets babili --minified
Error: Options {"evaluate":false,"mangle":true} passed to /var/www/xmaspeer/timetracker/public/node_modules/babel-preset-babili/lib/index.js which does not accept options. (While processing preset: "/var/www/xmaspeer/timetracker/public/node_modules/babel-preset-babili/lib/index.js")
    at /var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:320:17
    at Array.map (native)
    at OptionManager.resolvePresets (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/var/www/xmaspeer/timetracker/public/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/var/www/xmaspeer/timetracker/public/node_modules/babel-cli/lib/babel/util.js:50:22)
```

My `.babelrc`:

```
{
  "presets": [
    ["env",
    {
      "debug": false,
      "targets": {
        "browsers": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      },
      "modules": false
    }],
    ["babili", {
      "evaluate": false,
      "mangle": true
    }]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**Comment by dotnetCarpenter** [comment]
But if I just use `babilify` it works. `./node_modules/.bin/babili js/src/main.js --presets babili --minified`

Unfortunately, I have no idea how to get this working with my [rollup](http://rollupjs.org/) setup.

**Comment by FezVrasta** [comment]
Any updates on this?

**Comment by boopathi** [comment]
This is not yet published. Duplicate #338
