### ISSUE TITLE
Babili throwing error.

### ISSUE THREAD

**Issue by djforth** [babel/babili#351]
I'm not sure if I have missed something or if this is actual bug.  I've added babili to my babelrc file like so:

```
{
  "plugins": [
    "add-module-exports"
  ],
  "presets": [
    "babili",
    "es2015",
    "es2016",
    "es2017",
    "react"
  ],
  "env": {
    "development": {
      "plugins": ["react-hot-loader/babel"]
    }
  }
}
```

But when I run the code I get the following error

```
Error: Plugin 0 specified in "/Users/adrianstainforth/sites/modules/intertain-booking-js/node_modules/babel-preset-babili/lib/index.js" provided an invalid property of "name"
    at Plugin.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:127:13)
    at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:167:12)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:325:16)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)

```
Not sure if there is a package conflicting or if there is a bug

#Edit 

I reduced the babelrc to:

```
{
  "presets": [
    "babili",
    "es2015",
    "react"
  ]
}
```

still getting the same error

**Comment by kangax** [comment]
Does it happen without react and/or es2015? What happens if you change the order of presets?

**Comment by boopathi** [comment]
Upgrade babel-core to recent versions ... I think you're using an old verison of babel-core...

**Comment by djforth** [comment]
Ah ha cracked it, so what I didn't realise is you can build from babel-core e.g.

`BABEL_ENV=production babel src -x '.js','.jsx' -d lib`

I hadn't realised I hadn't installed babel-cli (which I meant too), installed this and all ran beautifully.
