### ISSUE TITLE
Parts of code not executed anymore after minification

### ISSUE THREAD

**Issue by MichaelKohler** [babel/babili#483]
I'm using babili through the babili-webpack-plugin on an express-based project. It seems that certain parts of the code won't be run without error once I'm using that plugin.

Steps to reproduce:
1) Checkout https://github.com/MichaelKohler/sandbox-minify-error-babili-webpack-plugin
2) npm install
3) ./node_modules/backpack-core/bin/backpack build
4) node dist/error.js
5) head to localhost:3000 and observe the terminal output

Output:
```
Example app listening on port 3000!
Error: hiiii im wrong!
    at /Users/mkohler/projects/error-test/dist/error.js:1:636
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mkohler/projects/error-test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mkohler/projects/error-test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/mkohler/projects/error-test/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
```

However, due to the Error being thrown, I would expect the error handler to kick in and log my console.log here: https://github.com/MichaelKohler/sandbox-minify-error-babili-webpack-plugin/blob/master/index.js#L10 . This does not happen.

When I now remove the plugin definition in https://github.com/MichaelKohler/sandbox-minify-error-babili-webpack-plugin/blob/master/backpack.config.js#L13 and run the build and node commands from above again, I get the following output:

```
Example app listening on port 3000!
let me log myself.. I should be fine, right? Error: hiiii im wrong!
    at /Users/mkohler/projects/error-test/dist/error.js:78:8
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mkohler/projects/error-test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mkohler/projects/error-test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mkohler/projects/error-test/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/mkohler/projects/error-test/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/mkohler/projects/error-test/node_modules/express/lib/router/layer.js:95:5)
```

This is exactly how I would expect it to work as I now see the console.log.

Could somebody have a look at this and tell me if I'm doing something wrong or if that really is a bug in babili?

Feel free to ask any questions you might have, I'm happy to answer them :)

**Comment by hzoo** [comment]
Hey @MichaelKohler! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vigneshshanmugam** [comment]
@MichaelKohler Just curios, why do you want to minify your server code?

**Comment by neophob** [comment]
@boopathi is this issue resolved?

**Comment by boopathi** [comment]
@neophob Yes. 

Not sure what the issue is. But with latest master, both `node index.js` and `node dist/error.js` have the same output.

**Comment by neophob** [comment]
will check, thanks!
