### ISSUE TITLE
Simplify NPE

### ISSUE THREAD

**Issue by postspectacular** [babel/babili#516]
I've been encountering a crash related to [this commit](https://github.com/babel/babili/commit/4ef735e451347eed49920632154f77c2363d7d24#diff-05684bffcab704dd5d3842adbf921357R1511). What's needed is a simple check that the `getFunctionParent()` result is non-null before attempting to access `.scope`, else you might get this:

```
TypeError: bundle.js: Cannot read property 'scope' of null
    at .../node_modules/babel-plugin-minify-simplify/lib/index.js:1504:42
    at Array.every (native)
    at genericEarlyExitTransform (.../babel-plugin-minify-simplify/lib/index.js:1473:29)
    at earlyReturnTransform (.../babel-plugin-minify-simplify/lib/index.js:1437:9)
    at PluginPass.exit (.../babel-plugin-minify-simplify/lib/index.js:528:11)
```

I've patched that line and it's working for me:

```js
const refp = ref.getFunctionParent();
if (!refp || refp.scope !== path.scope) return false;
```

**Comment by boopathi** [comment]
Duplicate #455
