### ISSUE TITLE
Don't use path.replaceWith() with a source string, use path.replaceWithSourceString()

### ISSUE THREAD

**Issue by INRIX-Xiaodi-Huang** [babel/babili#576]
ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`

Seems to be the result of this change : 
https://github.com/babel/babili/pull/543/files

**Comment by boopathi** [comment]
Thanks. Do you have a small snippet as input to reproduce this ?

**Comment by INRIX-Xiaodi-Huang** [comment]
Our codebase is pretty large. I am not sure what caused this error when minifying. I was using the babili webpack plugin.

**Comment by MDendura** [comment]
@INRIX-Xiaodi-Huang I've had the same error when updating babili-webpack-plugin from 0.0.11 to 0.1.1. Are you using that too?

**Comment by arthurmuchir** [comment]
Using babili version 0.1.2 I got the error

**Comment by boopathi** [comment]
Can you share the stack trace ?

**Comment by arthurmuchir** [comment]
```
Error: /Users/arthur/Documents/jean/gabrielle.js: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`
    at NodePath.replaceWith (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/path/replacement.js:139:11)
    at swap (/Users/arthur/Documents/jean/node_modules/babel-plugin-minify-constant-folding/lib/index.js:42:10)
    at PluginPass.CallExpression (/Users/arthur/Documents/jean/node_modules/babel-plugin-minify-constant-folding/lib/index.js:171:16)
    at newFn (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/arthur/Documents/jean/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by damianobarbati** [comment]
same here! +1

**Comment by boopathi** [comment]
/cc @j-f1 Do you know why this happens in the swap function ?

https://github.com/babel/babili/blob/7e2b315e37fc6392dbe05acf9463520d05434f56/packages/babel-plugin-minify-constant-folding/src/index.js#L34

**Comment by j-f1** [comment]
@boopathi I have no idea. It appears that all of the methods used return nodes. Can anyone provide an example snippet that fails?

**Comment by michaeltrim** [comment]
+1

**Comment by j-f1** [comment]
@michaeltrim Can you provide an example code snippet that fails?

**Comment by johnryan** [comment]
@j-f1 Any suggestions for how to figure out what line of code is failing? There's not much in the stack trace so finding the failing chunk of code seems pretty impossible in a large project.

**Comment by damianobarbati** [comment]
guys I have no way to provide snippets for the fail :(

**Comment by michaeltrim** [comment]
Not sure how to provide a code snippet that fails.

I get the Error: 

`ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()``

when I run yarn run build-main and do stack trace before the error is thrown I get, not sure if that helps:

at NodePath.replaceWith (/myapp/node_modules/babel-traverse/lib/path/replacement.js:140:13)
    at swap (/myapp/node_modules/babel-plugin-minify-constant-folding/lib/index.js:42:10)
    at PluginPass.CallExpression (/myapp/node_modules/babel-plugin-minify-constant-folding/lib/index.js:171:16)
    at newFn (/myapp/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/myapp/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/myapp/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/myapp/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/myapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/myapp/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/myapp/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/myapp/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/myapp/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/myapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/myapp/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/myapp/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/myapp/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/myapp/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/myapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/myapp/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/myapp/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/myapp/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/myapp/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/myapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/myapp/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/myapp/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/myapp/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/myapp/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/myapp/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/myapp/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/myapp/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/myapp/node_modules/babel-traverse/lib/index.js:114:17)

**Comment by michaeltrim** [comment]
I can see that the method path.replaceWith() is getting passed a string of "[object Object]"

**Comment by j-f1** [comment]
@michaeltrim Can you try replacing `node_modules/babel-plugin-minify-constant-folding/lib/index.js` with [this patched version](https://github.com/babel/babili/blob/d8c30c209ea88ad9678667580503537da4f8dbf4/packages/babel-plugin-minify-constant-folding/src/index.js) to see if that fixes it?

**Comment by michaeltrim** [comment]
@j-f1 That has fixed the error when running yarn run build-main, thank you.

yarn run package still doesn't complete but this may be unrelated just doing some investigation and will let you know.

**Comment by michaeltrim** [comment]
@j-f1 So the build does eventually work but I'm getting an out of memory error in the source map generator, not sure if this is connected but it didn't occur before

] 
[1] <--- Last few GCs --->
[1] 
[1] [1887:0x102801600]   428064 ms: Mark-sweep 1398.8 (1570.2) -> 1398.8 (1570.2) MB, 2901.9 / 0.0 ms  allocation failure GC in old space requested
[1] [1887:0x102801600]   431103 ms: Mark-sweep 1398.8 (1570.2) -> 1398.6 (1539.2) MB, 3038.7 / 0.0 ms  last resort 
[1] [1887:0x102801600]   434050 ms: Mark-sweep 1398.6 (1539.2) -> 1398.6 (1539.2) MB, 2946.1 / 0.0 ms  last resort 
[1] 
[1] 
[1] <--- JS stacktrace --->
[1] 
[1] ==== JS stack trace =========================================
[1] 
[1] Security context: 0x1781caa29891 <JS Object>
[1]     2: addMapping(aka SourceMapGenerator_addMapping) [/myapp/node_modules/babel-generator/node_modules/source-map/lib/source-map-generator.js:~94] [pc=0x3c00c07f75d0](this=0x3b3ccc65e509 <a SourceMapGenerator with map 0x3e8f0d3f4da1>,aArgs=0x30deb9bd3279 <an Object with map 0x3e8f0d3fa289>)
[1]     3: arguments adaptor frame: 3->1
[1]     4: InnerArrayForEa...
[1] 
[1] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[1]  1: 
[1] node::Abort() [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  4: v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  5: 
[1] v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  6: 
[1] v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/michaeltrim/.nvm/versions/node/v8.1.2/bin/node]
[1]  7: 0x3c00bf40437d
[1] npm run build-rendere

**Comment by michaeltrim** [comment]
Believe memory issue related to https://github.com/babel/babili/issues/332

**Comment by frzi** [comment]
@j-f1 This patch fixed the issue for me as well. Thanks!

**Comment by damianobarbati** [comment]
@j-f1 is a patch about to be release soon?

**Comment by j-f1** [comment]
I was just checking to see if that fixed the problem. The PR above includes that fix.

**Comment by Xazzzi-CT** [comment]
Is this on npm yet? Asking because i still get this error message.

**Comment by MikeLP** [comment]
It's really urgent.

**Comment by ahumphreys87** [comment]
I've downgraded to 0.0.11 while waiting. If it's breaking production builds
then you could do the same.

I think they said it would be released this afternoon.  If downgrading is
too much trouble

**Comment by damianobarbati** [comment]
Just tried the 0.1.1 and it's broken as well 😱

**Comment by ahumphreys87** [comment]
0.0.11

**Comment by damianobarbati** [comment]
@ahumphreys87 yep, using that for now thanks!

**Comment by ahumphreys87** [comment]
Awesome, fingers crossed the fix version won't be long

**Comment by vigneshshanmugam** [comment]
New version is released now with this fix https://github.com/babel/babili/releases/tag/babili%400.1.4

**Comment by damianobarbati** [comment]
Thanks @vigneshshanmugam! Should that fix this error? Still getting it with:
```
        "babili": "^0.1.4",
        "babili-webpack-plugin": "^0.1.1",
```

**Comment by LeeeeeeM** [comment]
problems with babel-traverse...em...
