### ISSUE TITLE
minify-dead-code-elimination remove-use-strict fails with async/await

### ISSUE THREAD

**Issue by swernerx** [babel/babili#641]
#### Input Code

```js
async function wait() {
  await loadData()
}
```

#### Actual Output

Throws the following error:

```
TypeError: ./__tests__/__fixtures__/es2017_async-await.js: block.get(...).filter is not a function
      
      at getUseStrictDirectives (node_modules/babel-plugin-minify-dead-code-elimination/lib/remove-use-strict.js:50:34)
      at removeUseStrict (node_modules/babel-plugin-minify-dead-code-elimination/lib/remove-use-strict.js:21:20)
      at PluginPass.exit (node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:844:13)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:117:8)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)
      at Function.Object.<anonymous>.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
```

#### Expected Output

Somewhat like this:

```js
async function wait(){await loadData()}
```

#### Details

Plugin version: 0.1.7

**Comment by boopathi** [comment]
#602 fixes this. Will release a new version soon.
